version: 2
log-file: /tmp/efm.log #because efm doesn't support ~ or env vars
log-level: 0
root-markers:
  - .git/
lint-debounce: 1s

tools:
  dockerfile-hadolint: &dockerfile-hadolint
    prefix: hadolint
    lint-command: hadolint --no-color -
    lint-stdin: true
    lint-formats:
      - '-:%l %.%# %trror: %m'
      - '-:%l %.%# %tarning: %m'
      - '-:%l %.%# %tnfo: %m'

  lua-selene: &lua-selene
    prefix: selene
    lint-command: selene --config ~/.config/helix/selene/selene.toml --display-style Quiet -
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats: 
      - '%f:%l:%c: %trror%m'
      - '%f:%l:%c: %tarning%m'
      - '%f:%l:%c: %tote%m'

  php-phpstan: &php-phpstan
    prefix: phpstan
    lint-command: ./vendor/bin/phpstan analyze --no-progress --no-ansi --error-format=raw '${INPUT}'
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - '%.%#:%l:%m'

  # php-cs-fixer: &php-cs-fixer
  #   format-command: php-cs-fixer fix --no-ansi --using-cache=no --no-interaction --quiet '${INPUT}'
  #   format-stdin: false
  
  # python-mypy: &python-mypy
  #   prefix: mypy
  #   lint-command: dmypy run --timeout 300 -- --strict --show-column-numbers
  #   lint-stdin: false
  #   lint-ignore-exit-code: true
  #   lint-formats:
  #     - '%f:%l:%c: %trror: %m'
  #     - '%f:%l:%c: %tarning: %m'
  #     - '%f:%l:%c: %tote: %m'

  # sh-shellcheck: &sh-shellcheck
  #   prefix: shellcheck
  #   lint-command: shellcheck --color=never --format=gcc -
  #   lint-ignore-exit-code: true
  #   lint-stdin: true
  #   lint-formats:
  #     - '-:%l:%c: %trror: %m'
  #     - '-:%l:%c: %tarning: %m'
  #     - '-:%l:%c: %tote: %m'

  c-gcc: &c-gcc
    prefix: gcc
    lint-command: gcc -x c -std=c2x -Wall -Wextra -pedantic -pedantic-errors -Wformat=2 -Wformat-overflow=2 -Wformat-signedness -Wformat-truncation=2 -Wnull-dereference -fdelete-null-pointer-checks -Wuninitialized -Winit-self -Wswitch-enum -fstrict-aliasing -Wstrict-flex-arrays -fstrict-flex-arrays=2 -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=noreturn -Wsuggest-attribute=malloc -Wsuggest-attribute=format -Wsuggest-attribute=cold -Walloc-zero -Walloca -ftree-vrp -Wduplicated-branches -Wduplicated-cond -Wtrampolines -Wfloat-equal -Wtraditional-conversion -Wshadow -Wunsafe-loop-optimizations -Wundef -Wbad-function-cast -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Wjump-misses-init -Wlogical-op -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wpacked -Wpadded -Wredundant-decls -Wnested-externs -Winline -Wvector-operation-performance -Wno-vla -Wstack-protector -fstack-protector -fno-diagnostics-color -fanalyzer '${INPUT}'
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - '%.%#:%l:%c: %trror: %m'
      - '%.%#:%l:%c: %tarning: %m'
      - '%.%#:%l:%c: %tnfo: %m'
      - '-:%l:%c: %trror: %m'

  c-cppcheck: &c-cppcheck
    prefix: cppcheck
    lint-command: cppcheck --enable=all --disable=unusedFunction --inconclusive -j 5 --language=c --library=std,posix --quiet --std=c23 '${INPUT}'
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'
    root-markers:
      - 'compile_flags.txt'
      - 'compile_commands.json'
      - 'CmakeLists.txt'

languages:
  dockerfile:
    - <<: *dockerfile-hadolint

  php:
    - <<: *php-phpstan
    # - <<: *php-cs-fixer

  lua:
    - <<: *lua-selene

  # python:
  #   - <<: *python-mypy

  sh:
    # - <<: *sh-shellcheck

  c:
    - <<: *c-gcc
    - <<: *c-cppcheck
