# everforest_dark|gruvbox_dark_hard|gruvbox_dark_soft|zed_onedark
# catppuccin_frappe|catppuccin_macchiato|catppuccin_mocha|pop-dark
# ayu_dark|ayu_mirage|kanagawa|new_moon
theme = "gruvbox" # everforest_dark

[editor]
scrolloff = 9
mouse = false
line-number = "relative"
cursorline = true
cursorcolumn = false
auto-completion = true
auto-format = true
preview-completion-insert = true
bufferline = "always"
color-modes = true
text-width = 80
insert-final-newline = true
auto-pairs = true
end-of-line-diagnostics = "disable"

[editor.statusline]
left = [
  "mode",
  "version-control",
  "file-modification-indicator",
  "read-only-indicator",
]
center = ["file-name"]
right = [
  "spinner",
  "diagnostics",
  "workspace-diagnostics",
  "position",
  "register",
  "selections",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"

[editor.lsp]
enable = true
auto-signature-help = true
display-inlay-hints = true
snippets = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.auto-save]
focus-lost = false
after-delay.enable = true
after-delay.timeout = 60000 # 1 min after last edit

[editor.search]
smart-case = true
wrap-around = true

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "▏" # "┊", "┆"
skip-levels = 1

[editor.gutters]
layout = ["diff", "line-numbers", "diagnostics"]

[editor.gutters.line-numbers]
min-width = 1

[editor.soft-wrap]
enable = true
max-wrap = 30
max-indent-retain = 0
wrap-at-text-width = true

[editor.smart-tab]
enable = true
supersede-menu = true

[editor.inline-diagnostics]
cursor-line = "info"
other-lines = "hint"
max-wrap = 40
max-diagnostics = 20

[keys.normal]
C-q = ":quit-all"
C-s = ":write"
C-r = ":config-reload"
A-s = "save_selection"
A-w = ":buffer-close"
# Wipe and edit the current line from cursor position
D = [ "extend_to_line_bounds", "change_selection"]
esc = ["collapse_selection", "keep_primary_selection"]
# Mark line and move with them up/down
# https://github.com/helix-editor/helix/discussions/5764#discussioncomment-4840408
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
# Duplicate lines up/down
# https://github.com/helix-editor/helix/issues/3680#issuecomment-1399443274
S-A-j = ["extend_to_line_bounds", "yank", "open_below", "normal_mode", "replace_with_yanked", "collapse_selection"]
S-A-k = ["extend_to_line_bounds", "yank", "open_above", "normal_mode", "replace_with_yanked", "collapse_selection"]
S-space = ["half_page_up"]
# a = ["append_mode", "collapse_selection"] # Remove the selection when entering insert mode with 'a'  

[keys.normal.space]
# "." = "file_picker_in_current_buffer_directory"

[keys.insert]
C-s = ["normal_mode", ":write", "insert_mode"]
A-s = "commit_undo_checkpoint"
# Duplicate lines up/down
# https://github.com/helix-editor/helix/issues/3680#issuecomment-1399443274
S-A-j = ["normal_mode", "extend_to_line_bounds", "yank", "open_below", "replace_with_yanked", "collapse_selection"]
S-A-k = ["normal_mode", "extend_to_line_bounds", "yank", "open_above", "replace_with_yanked", "collapse_selection"]
